INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5)._T','en','All currencies of denomination','_T'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5)._X','en','Not specified','_X'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5)._Z','en','Not applicable','_Z'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ADF','en','Andorran franc (1-1 peg to the French franc)','ADF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ADP','en','Andorran peseta (1-1 peg to the Spanish peseta)','ADP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AED','en','United Arab Emirates dirham','AED'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AFA','en','Afghanistan afghani (old)','AFA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AFN','en','Afghanistan, Afghanis','AFN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ALL','en','Albanian lek','ALL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AMD','en','Armenian dram','AMD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ANG','en','Netherlands Antillean guilder','ANG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AOA','en','Angolan kwanza','AOA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AON','en','Angolan kwanza (old)','AON'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AOR','en','Angolan kwanza readjustado (old)','AOR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ARS','en','Argentine peso','ARS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ATS','en','Austrian schilling','ATS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AUD','en','Australian dollar','AUD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AWG','en','Aruban florin/guilder','AWG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AZM','en','Azerbaijanian manat (old)','AZM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).AZN','en','Azerbaijan, manats','AZN');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BAM','en','Bosnia-Hezergovinian convertible mark','BAM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BBD','en','Barbados dollar','BBD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BDT','en','Bangladesh taka','BDT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BEF','en','Belgian franc','BEF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BEL','en','Belgian franc (financial)','BEL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BGL','en','Bulgarian lev (old)','BGL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BGN','en','Bulgarian lev','BGN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BHD','en','Bahraini dinar','BHD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BIF','en','Burundi franc','BIF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BMD','en','Bermudian dollar','BMD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BND','en','Brunei dollar','BND'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BOB','en','Bolivian boliviano','BOB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BRL','en','Brazilian real','BRL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BSD','en','Bahamas dollar','BSD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BTN','en','Bhutan ngultrum','BTN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BWP','en','Botswana pula','BWP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BYB','en','Belarussian rouble (old)','BYB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BYR','en','Belarus, Rubles','BYR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).BZD','en','Belize dollar','BZD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CAD','en','Canadian dollar','CAD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CD','en','National currency per US dollar (unit for exchange rates and PPP)','CD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CDF','en','Congo franc (ex Zaire)','CDF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CE','en','National currency per Euro (unit for exchange rates and PPP)','CE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CHE','en','WIR Euro','CHE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CHF','en','Swiss franc','CHF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CHW','en','WIR Franc','CHW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CLF','en','Unidades de fomento','CLF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CLP','en','Chilean peso','CLP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CNY','en','Chinese yuan renminbi','CNY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).COP','en','Colombian peso','COP');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).COU','en','Unidad de Valor Real','COU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CRC','en','Costa Rican colon','CRC'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CSD','en','Serbian dinar (old)','CSD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CUP','en','Cuban peso','CUP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CVE','en','Cape Verde escudo','CVE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CYP','en','Cypriot pound','CYP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).CZK','en','Czech koruna','CZK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).DEM','en','German mark','DEM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).DJF','en','Djibouti franc','DJF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).DKK','en','Danish krone','DKK');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).DOP','en','Dominican peso','DOP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).DY','en','Days','DY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).DZD','en','Algerian dinar','DZD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E0','en','Euro area changing composition vis-a-vis the EER-12 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB and US)','E0'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E1','en','Euro area-18 countries vis-a-vis the EER-20 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, BG, CZ, LT, HU, PL, RO, HR and CN)','E1'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E2','en','Euro area-18 countries vis-a-vis the EER-19 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, BG, CZ, LT, HU, PL, RO, and CN)','E2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E3','en','Euro area-18 countries vis-a-vis the EER-39 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, BG, CZ, LT, HU, PL, RO, CN, DZ, AR, BR, CL, HR, IS, IN, ID, IL, MY, MX, MA, NZ, PH, RU, ZA, TW, TH, TR and VE)','E3'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E4','en','Euro area-18 countries vis-a-vis the EER-12 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB and US)','E4'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E5','en','Euro area-19 countries vis-a-vis the EER-19 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, BG, CZ, HU, PL, RO, HR and CN)','E5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E6','en','Euro area-19 countries vis-a-vis the EER-18 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, BG, CZ, HU, PL, RO, and CN)','E6');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E7','en','Euro area-19 countries vis-a-vis the EER-38 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, BG, CZ, HU, PL, RO, CN, DZ, AR, BR, CL, HR, IS, IN, ID, IL, MY, MX, MA, NZ, PH, RU, ZA, TW, TH, TR and VE)','E7'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).E8','en','Euro area-19 countries vis-a-vis the EER-12 group of trading partners (AU, CA, DK, HK, JP, NO, SG, KR, SE, CH, GB and US)','E8'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ECS','en','Ecuador sucre (old)','ECS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EEK','en','Estonian kroon','EEK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EGP','en','Egyptian pound','EGP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ERN','en','Erytrean nafka','ERN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ESP','en','Spanish peseta','ESP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ETB','en','Ethiopian birr','ETB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR','en','Euro','EUR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_ACTIVITY','en','Euro; ratio to total activity','EUR_R_ACTIVITY');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B1G','en','Euro; ratio to gross value added.','EUR_R_B1G'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B1GQ','en','Euro; ratio to gross domestic product.','EUR_R_B1GQ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B1GQ_L','en','Euro; ratio to gross domestic product (chained linked volume)','EUR_R_B1GQ_L'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B1GQ_LA','en','Euro; ratio to gross domestic product (annual levels)','EUR_R_B1GQ_LA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B2','en','Euro; ratio to EU15','EUR_R_B2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B4','en','Euro; ratio to EU27','EUR_R_B4'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_B5','en','Euro; ratio to EU28','EUR_R_B5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_F5','en','Euro; ratio to equity and investment fund shares','EUR_R_F5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_I6','en','Euro; ratio to Euro Area 17','EUR_R_I6'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_I7','en','Euro; ratio to Euro Area 18','EUR_R_I7');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_I8','en','Euro; ratio to Euro Area 19','EUR_R_I8'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_POP','en','Euro; ratio to total population','EUR_R_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).EUR_R_U2','en','Euro; ratio to Euro Area (changing composition)','EUR_R_U2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).FIM','en','Finnish markka','FIM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).FJD','en','Fiji dollar','FJD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).FKP','en','Falkland Islands pound','FKP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).FRF','en','French franc','FRF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).FT','en','Full time equivalent','FT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).FT_R_ACTIVITY','en','Full time equivalents; ratio to total activity','FT_R_ACTIVITY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GBP','en','UK pound sterling','GBP');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GEL','en','Georgian lari','GEL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GGP','en','Guernsey, Pounds','GGP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GHC','en','Ghanaian cedi (old)','GHC'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GHS','en','Ghana Cedi','GHS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GIP','en','Gibraltar pound','GIP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GMD','en','Gambian dalasi','GMD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GNF','en','Guinea franc','GNF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GR','en','Grams','GR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GRD','en','Greek drachma','GRD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GTQ','en','Guatemalan quetzal','GTQ');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GWP','en','Guinea-Bissau Peso','GWP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).GYD','en','Guyanan dollar','GYD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H1','en','Euro area 18&apos;s currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, CY, EE, LV,  MT, SK)','H1'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H10','en','ECB EER-38 group of currencies and Euro area (latest composition) currencies (FR,BE,LU,NL,DE,IT,IE,PT,ES,FI,AT,GR,SI,AU,CA,CN,DK,HK,JP,NO,SG,KR,SE,CH,GB,US,CY,CZ,EE,HU,LV,LT,MT,PL,SK,BG,RO,NZ,DZ,AR,BR,HR,IN,ID,IL,MY,MX,MA,PH,RU,ZA,TW,TH,TR,IS,CL,VE)','H10'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H11','en','ECB EER-19 group of currencies and Euro area (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, CY, CZ, EE, HU, LV, LT, MT, PL, SK, BG, RO, HR)','H11'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LT','en','Litres','LT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H2','en','ECB EER-12 group of currencies and Euro area&apos;s (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, CY, EE, LV,  MT, SK, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US)','H2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H3','en','ECB EER-20 group of currencies and Euro area&apos;s (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, CY, CZ, EE, HU, LV, LT, MT, PL, SK, BG, RO)','H3'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H36','en','European Commission IC-36 group of currencies (European Union 27 Member States, i.e. BE, DE, EE, GR, ES, FR, IE, IT, CY, LU, NL, MT, AT, PT, SI, SK, FI, BG, CZ, DK, LV, LT, HU, PL, RO, SE, GB, and US, AU, CA, JP, MX, NZ, NO, CH, TR)','H36'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H37','en','European Commission IC-37 group of currencies (European Union 28 Member States, i.e. BE, DE, EE, GR, ES, FR, IE, IT, CY, LU, NL, MT, AT, PT, SI, SK, FI, BG, CZ, DK, HR, LV, LT, HU, PL, RO, SE, GB, and US, AU, CA, JP, MX, NZ, NO, CH, TR)','H37');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H4','en','ECB EER-40 group of currencies and Euro area&apos;s (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, CY, CZ, EE, HU, LV, LT, MT, PL, SK, BG, RO, NZ, DZ, AR, BR, HR, IN, ID, IL, MY, MX, MA, PH, RU, ZA, TW, TH, TR, IS, CL, VE)','H4'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H5','en','ECB EER-21 group of currencies and Euro area&apos;s (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, CY, CZ, EE, HU, LV, LT, MT, PL, SK, BG, RO, HR)','H5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H6','en','ECB EER-12 group of currencies and Euro area&apos;s  (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, CY, CZ, EE, HU, LV, LT, MT, PL, SK, BG, RO, HR, TR and RU)','H6'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H7','en','Euro area 19 currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, CY, EE, LT, LV, MT, SK)','H7'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H8','en','ECB EER-12 group of currencies and Euro area (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, CY, EE, LT, LV, MT, SK, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US)','H8'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).H9','en','ECB EER-18 group of currencies and Euro area (latest composition) currencies (FR, BE, LU, NL, DE, IT, IE, PT, ES, FI, AT, GR, SI, AU, CA, CN, DK, HK, JP, NO, SG, KR, SE, CH, GB, US, CY, CZ, EE, HU, LV, LT, MT, PL, SK, BG, RO)','H9'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HKD','en','Hong Kong dollar','HKD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HKQ','en','Hong Kong dollar (old)','HKQ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HNL','en','Honduran lempira','HNL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HR','en','Hours','HR');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HRK','en','Croatian kuna','HRK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HTG','en','Haitian gourde','HTG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HUF','en','Hungarian forint','HUF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HW','en','Hours worked','HW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).HW_R_ACTIVITY','en','Hours worked; ratio to total activity','HW_R_ACTIVITY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).IDR','en','Indonesian rupiah','IDR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).IEP','en','Irish pound','IEP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ILS','en','Israeli shekel','ILS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).IMP','en','Isle of Man, Pounds','IMP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).INR','en','Indian rupee','INR');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).IQD','en','Iraqi dinar','IQD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).IRR','en','Iranian rial','IRR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ISK','en','Iceland krona','ISK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ITL','en','Italian lira','ITL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).IX','en','Index','IX'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).JB','en','Jobs','JB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).JB_R_ACTIVITY','en','Jobs; ratio to total activity','JB_R_ACTIVITY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).JEP','en','Jersey, Pounds','JEP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).JMD','en','Jamaican dollar','JMD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).JOD','en','Jordanian dinar','JOD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).JPY','en','Japanese yen','JPY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KES','en','Kenyan shilling','KES'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KG','en','Kilograms','KG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KGS','en','Kyrgyzstan som','KGS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KHR','en','Kampuchean real (Cambodian)','KHR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KL','en','Kilolitres','KL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KMF','en','Comoros franc','KMF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KPW','en','Korean won (North)','KPW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KRW','en','Korean won (Republic)','KRW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KWD','en','Kuwait dinar','KWD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KYD','en','Cayman Islands dollar','KYD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).KZT','en','Kazakstan tenge','KZT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LAK','en','Lao kip','LAK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LBP','en','Lebanese pound','LBP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LKR','en','Sri Lanka rupee','LKR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LRD','en','Liberian dollar','LRD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LSL','en','Lesotho loti','LSL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LTL','en','Lithuanian litas','LTL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LUF','en','Luxembourg franc','LUF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LVL','en','Latvian lats','LVL');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).LYD','en','Libyan dinar','LYD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MAD','en','Moroccan dirham','MAD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MD','en','Man Days','MD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MDL','en','Moldovian leu','MDL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MGA','en','Madagascar, Ariary','MGA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MGF','en','Malagasy franc','MGF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MH','en','Months','MH'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MKD','en','Macedonian denar','MKD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MMK','en','Myanmar kyat','MMK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MNT','en','Mongolian tugrik','MNT');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MOP','en','Macau pataca','MOP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MQ','en','Square Metres','MQ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MRO','en','Mauritanian ouguiya','MRO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MTL','en','Maltese lira','MTL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MUR','en','Mauritius rupee','MUR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MVR','en','Maldive rufiyaa','MVR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MWK','en','Malawi kwacha','MWK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MXN','en','Mexican peso','MXN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MXP','en','Mexican peso (old)','MXP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MXV','en','Mexican Unidad de Inversion (UDI)','MXV');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MY','en','Man Years','MY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MYR','en','Malaysian ringgit','MYR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MZM','en','Mozambique metical (old)','MZM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).MZN','en','Mozambique, Meticais','MZN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NAD','en','Namibian dollar','NAD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NGN','en','Nigerian naira','NGN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NIO','en','Nicaraguan cordoba','NIO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NLG','en','Netherlands guilder','NLG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NOK','en','Norwegian krone','NOK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NPR','en','Nepaleese rupee','NPR');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).NZD','en','New Zealand dollar','NZD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).OMR','en','Oman Sul rial','OMR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).OZ','en','Ounces','OZ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PA','en','Percent per annum','PA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PAB','en','Panama balboa','PAB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PC','en','Percentage change','PC'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE','en','Euro, converted using purchasing power parities','PE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B2','en','Euro, converted using purchasing power parities; ratio to EU15','PE_R_B2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B4','en','Euro, converted using purchasing power parities; ratio to EU27','PE_R_B4'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B4_POP','en','Euro, converted using purchasing power parities; ratio to EU27 per capita','PE_R_B4_POP');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B5','en','Euro, converted using purchasing power parities; ratio to EU28','PE_R_B5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B5_EMP_HW','en','Euro, converted using purchasing power parities; ratio to EU28 hours worked','PE_R_B5_EMP_HW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B5_EMP_PS','en','Euro, converted using purchasing power parities; ratio to EU28 persons employed','PE_R_B5_EMP_PS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_B5_POP','en','Euro, converted using purchasing power parities; ratio to EU28 per capita','PE_R_B5_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I6','en','Euro, converted using purchasing power parities; ratio to EuroArea 17','PE_R_I6'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I7','en','Euro, converted using purchasing power parities; ratio to Euro Area 18','PE_R_I7'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I7_EMP_HW','en','Euro, converted using purchasing power parities; ratio to Euro Area 18 hours worked','PE_R_I7_EMP_HW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I7_EMP_PS','en','Euro, converted using purchasing power parities; ratio to Euro Area 18 persons employed','PE_R_I7_EMP_PS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I8','en','Euro, converted using purchasing power parities; ratio to Euro Area 19','PE_R_I8'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I8_EMP_HW','en','Euro, converted using purchasing power parities; ratio to Euro Area 19 hours worked','PE_R_I8_EMP_HW');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_I8_EMP_PS','en','Euro, converted using purchasing power parities; ratio to Euro Area 19 persons employed','PE_R_I8_EMP_PS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_POP','en','Euro, converted using purchasing power parities; ratio to total population.','PE_R_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PE_R_U2','en','Euro, converted using purchasing power parities; ratio to Euro Area (changing composition)','PE_R_U2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PEN','en','Peru nuevo sol','PEN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PGK','en','Papua New Guinea kina','PGK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PHP','en','Philippine peso','PHP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PKR','en','Pakistan rupee','PKR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PLN','en','Polish zloty','PLN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PLZ','en','Polish zloty (old)','PLZ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PN','en','Pure number','PN');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PO','en','Points','PO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PP','en','Purchasing power parities','PP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PS','en','Persons','PS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PS_R_ACTIVITY','en','Persons; ratio to total activity','PS_R_ACTIVITY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PT','en','Percent','PT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PTE','en','Portugese escudo','PTE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU','en','US dollar, converted using purchasing power parities','PU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B1G','en','US $, PPP converted, ratio to value added','PU_R_B1G'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B1G_S11','en','US $ , PPP converted, ratio to value added of non-financial corporations','PU_R_B1G_S11'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B1G_S12','en','US $, PPP converted, ratio to value added of financial corporations','PU_R_B1G_S12');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B1GQ','en','US $, PPP converted, ratio to gross domestic product','PU_R_B1GQ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B2G_S11','en','US $, PPP converted, ratio to gross operating surplus of non-financial corporations','PU_R_B2G_S11'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B2G_S12','en','US $ , PPP converted, ratio to gross operating surplus of financial corporations','PU_R_B2G_S12'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B6G_S1M','en','US $, PPP converted, ratio to household and NPISH gross disposable income','PU_R_B6G_S1M'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_B6N_S1M','en','US $, PPP converted, ratio to household and NPISH net disposable income','PU_R_B6N_S1M'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_F_S1M','en','US $, PPP converted, ratio to total household and NIPSH financial assets','PU_R_F_S1M'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_OTE','en','US $, PPP converted, ratio to total expenditure of General Government','PU_R_OTE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_P31_S1M_D','en','US $, PPP converted, deflated by final consumption of households and NPISH','PU_R_P31_S1M_D'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_P41_D','en','US $, PPP converted, deflated by actual individual consumption','PU_R_P41_D'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_P51G','en','US $, PPP converted, ratio to GFCF','PU_R_P51G');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_POP','en','Per capita, US $, PPP converted','PU_R_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PU_R_POP_PU_6O','en','Index per capita, US $, PPP converted,  OECD = 100','PU_R_POP_PU_6O'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).PYG','en','Paraguay guarani','PYG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).QAR','en','Qatari rial','QAR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RO','en','Ratio','RO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ROL','en','Romanian leu (old)','ROL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RON','en','Romanian leu','RON'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RSD','en','Serbian Dinar','RSD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RT','en','Interest rate','RT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RUB','en','Rouble','RUB');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RUR','en','Russian ruble (old)','RUR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).RWF','en','Rwanda franc','RWF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SAR','en','Saudi riyal','SAR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SBD','en','Solomon Islands dollar','SBD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SCR','en','Seychelles rupee','SCR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SDD','en','Sudanese dinar (old)','SDD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SDG','en','Sudan, Dinars','SDG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SDP','en','First sudanese Pound','SDP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SEK','en','Swedish krona','SEK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SGD','en','Singapore dollar','SGD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SHP','en','St. Helena pound','SHP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SIT','en','Slovenian tolar','SIT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SKK','en','Slovak koruna','SKK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SLL','en','Sierra Leone leone','SLL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SOS','en','Somali shilling','SOS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SPL','en','Seborga, Luigini','SPL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SRD','en','Suriname, Dollars','SRD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SRG','en','Suriname guilder (old)','SRG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SSP','en','South Sudanese Pound','SSP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).STD','en','Sao Tome and Principe dobra','STD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SVC','en','El Salvador colon','SVC'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SYP','en','Syrian pound','SYP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).SZL','en','Swaziland lilangeni','SZL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).THB','en','Thai bhat','THB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TJR','en','Tajikistan rouble (old)','TJR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TJS','en','Tajikistan, Somoni','TJS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TMM','en','Turkmenistan manat','TMM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TMT','en','Turkmenistan New Manat','TMT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TN','en','Tonnes','TN'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TND','en','Tunisian dinar','TND');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TOP','en','Tongan paanga','TOP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TPE','en','East Timor escudo (old)','TPE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TRL','en','Turkish lira (old)','TRL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TRY','en','Turkish lira','TRY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TTD','en','Trinidad and Tobago dollar','TTD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TVD','en','Tuvalu Dollars','TVD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TWD','en','New Taiwan dollar','TWD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).TZS','en','Tanzania shilling','TZS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).UAH','en','Ukraine hryvnia','UAH'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).UGX','en','Uganda Shilling','UGX');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).USD','en','US dollar','USD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).USD_R_CA','en','Dollars; Ratio to Current account','USD_R_CA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).USD_R_GS','en','Dollars; Ratio to Total goods and services','USD_R_GS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).USD_R_POP','en','Per capita, US $, exchange rates converted','USD_R_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).UT','en','Unit described in title','UT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).UYI','en','Uruguay Peso en Unidades Indexadas','UYI'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).UYU','en','Uruguayan peso','UYU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).UZS','en','Uzbekistan sum','UZS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).VEB','en','Venezuela bolivar (old)','VEB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).VEF','en','Bolivar Fuerte','VEF');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).VND','en','Vietnamese dong','VND'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).VUV','en','Vanuatu vatu','VUV'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).WST','en','Samoan tala','WST'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X1','en','All currencies except national domestic currency','X1'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X2','en','All currencies except: USD','X2'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X3','en','All currencies except EUR','X3'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X4','en','All currencies except: EUR, USD','X4'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X5','en','All currencies except: EUR,  JPY, USD','X5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X6','en','All currencies except: EUR, CHF, GBP, JPY, USD','X6'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).X7','en','All currencies except: EUR, USD, JPY, GBP, CHF, domestic currency','X7');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XAF','en','CFA franc / BEAC','XAF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XAG','en','Silver','XAG'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XAU','en','Gold','XAU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XBA','en','Bond Markets Unit European Composite Unit (EURCO)','XBA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XBB','en','Bond Markets Unit European Monetary Unit (E.M.U.-6)','XBB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XBC','en','Bond Markets Unit European Unit of Account 9 (E.U.A.-9)','XBC'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XBD','en','Bond Markets Unit European Unit of Account 17 (E.U.A.-17)','XBD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XCD','en','Eastern Caribbean dollar','XCD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDB','en','Currencies included in the SDR basket, gold and SDRs','XDB'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC','en','Domestic currency (incl. conversion to current currency made using a fix parity)','XDC');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1G','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to gross value added.','XDC_R_B1G'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1G_CY','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to annual moving sum of sector specific gross value added.','XDC_R_B1G_CY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1G_S11','en','percentage of value added of non-financial corporations','XDC_R_B1G_S11'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1G_S12','en','percentage of value added of financial corporations','XDC_R_B1G_S12'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1GQ','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to gross domestic product.','XDC_R_B1GQ'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1GQ_CY','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to the annual moving sum of gross domestic product','XDC_R_B1GQ_CY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1GQ_L','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to gross domestic product (chained linked volume)','XDC_R_B1GQ_L'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1GQ_LA','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to gross domestic product (annual levels)','XDC_R_B1GQ_LA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1N','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to net value added.','XDC_R_B1N'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B1N_CY','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to annual moving sum of sector specific net value added.','XDC_R_B1N_CY');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XPT','en','Platinum','XPT'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B2G_S11','en','percentage of gross operating surplus of non-financial corporations','XDC_R_B2G_S11'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B2G_S12','en','percentage of gross operating surplus of financial corporations','XDC_R_B2G_S12'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B6G_CY','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to the annual moving sum of sector specific gross disposable income','XDC_R_B6G_CY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B6G_POP','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to per capita  sector specific  gross disposable income','XDC_R_B6G_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B6G_S1M','en','percentage of household and NPISH gross disposable income','XDC_R_B6G_S1M'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B6GA_CY','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to the annual moving sum of sector specific gross disposable income, adjusted for the change in net equity of households in pension funds reserves.','XDC_R_B6GA_CY'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B6GA_POP','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to per capita sector specific gross disposable income, adjusted for the change in net equity of households in pension funds reserves.','XDC_R_B6GA_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_B6N_S1M','en','percentage of household and NPISH net disposable income','XDC_R_B6N_S1M'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_EMP','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to total employment.','XDC_R_EMP');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_EMP_HW','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to total employment in hours worked.','XDC_R_EMP_HW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_EMP_PS','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to total employment in persons.','XDC_R_EMP_PS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_F','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to sector specific assets/liabilities.','XDC_R_F'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_F_S1M','en','percentage of total household and NIPSH financial assets','XDC_R_F_S1M'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_F5','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to equity and investment fund shares','XDC_R_F5'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_F5_L','en','Number of times of liability of equity and investment fund shares','XDC_R_F5_L'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_F51_L','en','Number of times of liability of equity','XDC_R_F51_L'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_FD','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to sector specific financing.','XDC_R_FD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_FI','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to sector specific financial investment.','XDC_R_FI'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_GD','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to Maastricht debt.','XDC_R_GD');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_GF10','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to total expenditure in social protection.','XDC_R_GF10'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_I7','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to Euro area 18','XDC_R_I7'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_I8','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to Euro area 19','XDC_R_I8'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_OTE','en','percentage of total expenditure of General Government','XDC_R_OTE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_P31_S1M_D','en','national currency, deflated by final consumption of households and NPISH','XDC_R_P31_S1M_D'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_P41_D','en','national currency, deflated by actual individual consumption','XDC_R_P41_D'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_P51G','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to Gross fixed capital formation','XDC_R_P51G'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_POP','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to total population.','XDC_R_POP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_SAL_HW','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to employees in hours worked.','XDC_R_SAL_HW'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDC_R_SAL_PS','en','Domestic currency (incl. conversion to current currency made using a fix parity); ratio to employees in hours worked.','XDC_R_SAL_PS');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDM','en','Domestic currency (incl. conversion to current currency made using market exchange rate)','XDM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDO','en','Other currencies not included in the SDR basket, exc. gold and SDRs','XDO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XDR','en','Special Drawing Rights (S.D.R.)','XDR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XEU','en','European Currency Unit (E.C.U.)','XEU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XFO','en','Gold-Franc','XFO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XFU','en','UIC-Franc','XFU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XGO','en','Gold fine troy ounces','XGO'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XNC','en','Euro area non-participating foreign currency','XNC'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XOF','en','CFA franc / BCEAO','XOF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XPC','en','Euro area participating foreign currency','XPC');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XPD','en','Palladium','XPD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XPF','en','Pacific franc','XPF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XSU','en','Sucre','XSU'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XTS','en','Codes specifically reserved for testing purposes','XTS'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XUA','en','ADB Unit of Account','XUA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXCF','en','Exchange rate: currency of area per currency of counterpart area with conversion factor to fixed exchange rate
series','XXCF'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXCFA','en','Exchange rate (average): currency of area per currency of counterpart area with conversion factor to fixed exchange rate
series','XXCFA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXCFE','en','Exchange rate (end of period): currency of area per currency of counterpart area with conversion factor to fixed exchange rate
series','XXCFE'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXEXA','en','Exchange rate (average): currency of area per currency of counterpart area','XXEXA'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXEXE','en','Exchange rate (end of period): currency of area per currency of counterpart area','XXEXE');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXPP','en','Purchasing power parities: currency of area per currency of counterpart area','XXPP'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).XXX','en','Transactions where no currency is involved','XXX'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).YER','en','Yemeni rial','YER'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).YR','en','Years','YR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).YUM','en','Yugoslav dinar (old)','YUM'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ZAR','en','South African rand','ZAR'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ZMK','en','Zambian kwacha','ZMK'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ZWD','en','Zimbabwe dollar','ZWD'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ZWL','en','Fourth zimbabwe dollar','ZWL'),
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ZWN','en','Zimbabwe dollars (old)','ZWN');
INSERT INTO sdmx.[cl_unit] (urn,lang,description,code) VALUES
	 ('urn:sdmx:org.sdmx.infomodel.codelist.Code=IMF:CL_UNIT(1.5).ZWR','en','Third zimbabwe dollar','ZWR');