SELECT DISTINCT 
@@SERVERNAME AS [SERVER],
DB_NAME(dovs.database_id) DBName,
mf.physical_name PhysicalFileLocation,
dovs.logical_volume_name AS LogicalName,
dovs.volume_mount_point AS Drive,
CONVERT(INT,dovs.available_bytes/1048576.0) AS FreeSpaceInMB
,CONVERT(INT,(dovs.total_bytes-dovs.available_bytes)/1048576.0) AS UsedSpaceInMB
,CONVERT(INT,dovs.total_bytes/1048576.0) AS TotalSpaceInMB
,(CONVERT(numeric,(dovs.total_bytes-dovs.available_bytes)/1048576.00)/(CONVERT(numeric,dovs.total_bytes/1048576.00)))*100.000 as PercentUsed
,DA
FROM sys.master_files mf
CROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.FILE_ID) dovs
where dovs.database_id>4
ORDER BY FreeSpaceInMB ASC
GO

--select 151555.00/3145596.00
USE DBMONITOR
GO
CREATE TABLE SERVERLIST (
ID INT NOT NULL PRIMARY KEY,
[SERVER] VARCHAR(70) NOT NULL,
[NODE]  VARCHAR(70) NOT NULL,
[SO] VARCHAR(100) NOT NULL,
[NROCORES] TINYINT NOT NULL,
[MEMORY] INT NOT NULL
)


GO
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (1,'DATASQLSGR','ESCORPION','64-bit edition of Windows Server 2012 Standard',4,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (2,'VALTIRISDB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (3,'VARCGIS16DB','libra','Windows Server 2016 Standard',4,20480);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (4,'VARCGISDB','ESCORPION','64-bit edition of Windows Server 2012 Standard',4,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (5,'VARCGISMINVDB','libra','Windows Server 2016 Standard',4,20480);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (6,'VATENEADB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (7,'VATLANTEDB','ESCORPION','Windows Server 2016 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (8,'VBIDB','ESCORPION','Windows Server 2016 Standard',4,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (9,'VBIDEV','ESCORPION','Windows Server 2012 R2 Standard',4,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (10,'VBIGDATADB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (11,'VCENTAURODB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (12,'VCONPESDB','ESCORPION','Windows Server 2016 Standard',8,24576);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (13,'VDATAZENDB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (14,'VDDRSDB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (15,'VDELTADB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (16,'VDEV16DB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (17,'VDEV17DB','libra','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (18,'VDEVDB','ESCORPION','64-bit edition of Windows Server 2012 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (19,'VDEVOPSDB','libra','Windows Server 2016 Standard',4,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (20,'VDIESONLDB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (21,'VDIFP16DB','libra','Windows Server 2016 Standard',8,4678);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (22,'VDNPEPODB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (23,'VEADB','libra','Windows Server 2016 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (24,'vFauno','ESCORPION','64-bit edition of Windows Server 2012 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (25,'VFAUNODB','ESCORPION','Windows Server 2016 Standard',12,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (26,'VFORTIDB','ESCORPION','Windows Server 2016 Standard',8,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (27,'VGETDB','ESCORPION','Windows Server 2016 Standard',8,24576);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (28,'VGPBIDB','ESCORPION','Windows Server 2012 R2 Standard',16,61440);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (29,'VGPREPDB','ESCORPION','Windows Server 2012 R2 Standard',16,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (30,'VHUELLASDB','libra','Windows Server 2016 Standard',12,24576);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (31,'VKPTDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (32,'VKPTPRDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (33,'VMAPAI01PRDB','libra','Windows Server 2016 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (34,'VMAPAI02PRDB','libra','Windows Server 2016 Standard',16,32678);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (35,'VMAPAINV01DB','ESCORPION','Windows Server 2016 Standard',8,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (36,'VMAPAINV02DB','libra','Windows Server 2016 Standard',32,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (37,'VMAPAREGALIASDB','ESCORPION','64-bit edition of Windows Server 2012 Standard',8,24576);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (38,'VMOODLEDB','ESCORPION','Windows Server 2016 Standard',16,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (39,'VORFEODB','ESCORPION','Windows Server 2016 Standard',12,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (40,'VOSCDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (41,'VPNSCDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (42,'VPNSCDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (43,'VPROACTIVADBPR','ESCORPION','Windows Server 2012 R2 Standard',4,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (44,'VRIEPIDB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (45,'VRUAPPDB','ESCORPION','Windows Server 2016 Standard',2,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (46,'VSCOMDB16','ESCORPION','Windows Server 2016 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (47,'VSCOMDW16','ESCORPION','Windows Server 2016 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (48,'VSCVMM16DB','ESCORPION','Windows Server 2016 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (49,'VSCVMM19DB','ESCORPION','Windows Server 2019 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (50,'VSERVICIOSDB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (51,'VSICODISDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (52,'VSIIPODB','ESCORPION','Windows Server 2016 Standard',2,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (53,'VSIIPOPRDB','libra','Windows Server 2016 Standard',2,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (54,'VSINERGIADB','ESCORPION','Windows Server 2016 Standard',4,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (55,'VSISBEN16DB','libra','Windows Server 2016 Standard',32,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (56,'VSISBEN4DB','libra','Windows Server 2016 Standard',8,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (57,'VSISBEN4PRDB','libra','Windows Server 2016 Standard',8,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (58,'VSISBENCAPDB','libra','Windows Server 2016 Standard',8,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (59,'VSISBENCONS','libra','Windows Server 2012 R2 Standard',8,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (60,'VSISBENCONSDB','libra','Windows Server 2016 Standard',8,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (61,'VSISBENDEV','ESCORPION','Windows Server 2012 R2 Standard',8,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (62,'VSKY01DB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (63,'VSKY02DB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (64,'VSP1601DB','libra','Windows Server 2016 Standard',8,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (65,'VSP1602DB','libra','Windows Server 2016 Standard',8,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (66,'VSP16PRDB','ESCORPION','Windows Server 2016 Standard',4,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (67,'VSPDB','libra','Windows Server 2012 R2 Standard',48,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (68,'VSPDB02','ESCORPION','Windows Server 2012 R2 Standard',16,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (69,'VSPDEVDB','ESCORPION','Windows Server 2012 R2 Standard',8,24576);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (70,'VSPPR','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (71,'VSPPRDB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (72,'VSQLENT01','ESCORPION','64-bit edition of Windows Server 2012 Standard',12,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (73,'VSQLMSDB','ESCORPION','Windows Server 2016 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (74,'VSQLPTODB','ESCORPION','Windows Server 2012 R2 Standard',8,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (75,'VSQLSTA01','ESCORPION','64-bit edition of Windows Server 2012 Standard',8,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (76,'VSTIPMVRDB','ESCORPION','Windows Server 2012 R2 Standard',4,16384);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (77,'VSUIFP16DB','libra','Windows Server 2016 Standard',16,65536);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (78,'VTFS15DB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (79,'VVEEAMDB','ESCORPION','Windows Server 2019 Standard',8,32768);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (80,'VWSUSDB','ESCORPION','Windows Server 2012 R2 Standard',4,4096);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (81,'VZAFIRO16DB','libra','Windows Server 2016 Standard',6,12288);
INSERT INTO SERVERLIST (ID,[SERVER],NODE,SO,NROCORES,MEMORY) VALUES (82,'VZAFIRODB','ESCORPION','Windows Server 2012 R2 Standard',4,8192);
